### ISSUE TITLE
Pip installation does't work.

### ISSUE THREAD

**Issue by pendolf** [yunojuno/django-request-profiler#3]
```
$ pip install django-request—profiler
Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/pip/basecommand.py", line 232, in main
    status = self.run(options, args)
  File "/usr/local/lib/python2.7/site-packages/pip/commands/install.py", line 305, in run
    name, None, isolated=options.isolated_mode,
  File "/usr/local/lib/python2.7/site-packages/pip/req/req_install.py", line 181, in from_line
    isolated=isolated)
  File "/usr/local/lib/python2.7/site-packages/pip/req/req_install.py", line 54, in __init__
    req = pkg_resources.Requirement.parse(req)
  File "/usr/local/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2873, in parse
    reqs = list(parse_requirements(s))
  File "/usr/local/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2820, in parse_requirements
    "version spec")
  File "/usr/local/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2785, in scan_list
    raise ValueError(msg, line, "at", line[p:])
ValueError: ('Expected version spec in', 'django-request\xe2\x80\x94profiler', 'at', '\xe2\x80\x94profiler')
```

**Comment by hugorodgerbrown** [comment]
Hi @pendolf - I'm not sure if this answers the issue, but it looks like the second hyphen ('-') in your `pip install ` is a unicode char ('—').

Try this: `pip install django-request-profiler`

**Comment by pendolf** [comment]
Oh you are right! I just copy this command from your README.rst file please edit it.
